name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Run Bazel build
        run: bazel build //...

      - name: Run Bazel test
        run: bazel test //...

      - name: List open pull requests
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pullRequests = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });

            if (pullRequests.data.length === 0) {
              console.log('No open pull requests found.');
            } else {
              console.log(`Found ${pullRequests.data.length} open pull request(s):`);
              pullRequests.data.forEach(pr => {
                console.log(`#${pr.number}: ${pr.title} (by ${pr.user.login})`);
              });
            }
